before:
  hooks:
    - go mod tidy
builds:
  - id: gpt4batch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - CC=gcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    binary: gpt4batch

archives:
  - id: gpt4batch
    builds: ["gpt4batch"]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: "gpt4batch-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md